/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Classes.Studio;
import EDD.OurQueue;
import EDD.SimpleList;
import javax.swing.JFrame;
import javax.swing.ImageIcon;
import Main.App;
import Managers.ImagesManager;
import javax.swing.JScrollPane;
import Classes.Character;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;

/**
 *
 * @author HP-Probook
 */
public class Principal extends javax.swing.JFrame {

    private static Principal mainFrameInstance;
    private ImagesManager imagesManager;
    App app = App.getInstance();

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        // jframe config
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setTitle("Main Battle View");

        // Propiedades
        this.imagesManager = new ImagesManager();
        IAStatusLabel.setText("[...]");
        winnerLabel.setText("[...]");

        // Configurar el slider de velodiad 
        battleDurationSlider.setOpaque(false);
        battleDurationSlider.setMinimum(1);
        battleDurationSlider.setMaximum(15);
        battleDurationSlider.setValue(app.getBattleDuration());
        // Para mostrar las imágenes iniciales
    }

    public static synchronized Principal getPrincipalInstance() {
        if (getMainFrameInstance() == null) {
            setMainFrameInstance(new Principal());
        }
        return getMainFrameInstance();
    }

// Método para actualizar las colas con imágenes en el JScrollPane
    public void updateQueuesUI() {
        Studio firstStudio = app.getAdmin().getFirstStudio();
        Studio secondStudio = app.getAdmin().getSecondStudio();

        // Obtener las colas de prioridad de cada estudio
        OurQueue<Character> starWarsPriority1 = firstStudio.getPrior1_queue();
        OurQueue<Character> starWarsPriority2 = firstStudio.getPrior2_queue();
        OurQueue<Character> starWarsPriority3 = firstStudio.getPrior3_queue();
        OurQueue<Character> starWarsRQ = firstStudio.getReinforcement_queue();

        OurQueue<Character> starTrekPriority1 = secondStudio.getPrior1_queue();
        OurQueue<Character> starTrekPriority2 = secondStudio.getPrior2_queue();
        OurQueue<Character> starTrekPriority3 = secondStudio.getPrior3_queue();
        OurQueue<Character> starTrekRQ = secondStudio.getReinforcement_queue();

        // Asignar paneles a cada JScrollPane usando el nuevo método getImagesFromQueue
        updateQueueVisual(swQueue1, starWarsPriority1);
        updateQueueVisual(swQueue2, starWarsPriority2);
        updateQueueVisual(swQueue3, starWarsPriority3);
        updateQueueVisual(stQueue1, starTrekPriority1);
        updateQueueVisual(stQueue2, starTrekPriority2);
        updateQueueVisual(stQueue3, starTrekPriority3);

        updateQueueVisual(swReinQueue, starWarsRQ);
        updateQueueVisual(stReinQueue, starTrekRQ);
    }

    private void updateQueueVisual(JScrollPane scrollPane, OurQueue<Character> queue) {
        SimpleList<ImageIcon> images = getImagesManager().getImagesFromQueue(queue);

        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.X_AXIS));

        if (images == null || images.getSize() == 0) {
            JLabel emptyLabel = new JLabel("Sin imágenes disponibles");
            panel.add(emptyLabel);
        } else {
            for (int i = 0; i < images.getSize(); i++) {
                ImageIcon image = images.getValueByIndex(i);
                if (image != null) {
                    JLabel imageLabel = new JLabel(image);
                    panel.add(imageLabel);
                }
            }
        }

        scrollPane.setViewportView(panel);
    }


//    // Método para actualizar la imagen en el JPanel
//    public void updateStarWarsImageIcon(ImageIcon newImageIcon) {
//        this.SWImageLabel.setIcon(newImageIcon);
//        revalidate();
//        repaint();
//    }
//
//    public void updateStarTrekImageIcon(ImageIcon newImageIcon) {
//        this.STImageLabel.setIcon(newImageIcon);
//        revalidate();
//        repaint();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        jScrollPane6 = new javax.swing.JScrollPane();
        jSlider2 = new javax.swing.JSlider();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        roundCounterLabel = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        battleDurationSlider = new javax.swing.JSlider();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        jSlider4 = new javax.swing.JSlider();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        swReinQueue = new javax.swing.JScrollPane();
        jLabel15 = new javax.swing.JLabel();
        stReinQueue = new javax.swing.JScrollPane();
        FightPanel = new javax.swing.JPanel();
        IAStatusLabel = new javax.swing.JLabel();
        IAStatusTitle = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        stFighterNameLabel = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        swFighterNameLabel = new javax.swing.JLabel();
        winnerLabel = new javax.swing.JLabel();
        SWFighterCard = new javax.swing.JPanel();
        SWImageLabel = new javax.swing.JLabel();
        STFighterCard = new javax.swing.JPanel();
        STImageLabel = new javax.swing.JLabel();
        announcerLabel = new javax.swing.JLabel();
        swAgilityLabel = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        swHPLabel = new javax.swing.JLabel();
        swDefenseLabel = new javax.swing.JLabel();
        stHPLabel = new javax.swing.JLabel();
        stDefenseLabel = new javax.swing.JLabel();
        stAgilityLabel = new javax.swing.JLabel();
        SWQueuePanel = new javax.swing.JPanel();
        swQueue1 = new javax.swing.JScrollPane();
        swQueue2 = new javax.swing.JScrollPane();
        swQueue3 = new javax.swing.JScrollPane();
        jLabel13 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        SWLogoLabel = new javax.swing.JLabel();
        STQueuePanel = new javax.swing.JPanel();
        stQueue1 = new javax.swing.JScrollPane();
        stQueue2 = new javax.swing.JScrollPane();
        stQueue3 = new javax.swing.JScrollPane();
        jLabel7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        STLogoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 51, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 330, 90));

        jScrollPane5.setViewportView(jScrollPane6);

        jPanel4.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 330, 90));
        jPanel4.add(jSlider2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, 330, 60));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("Ajuste la velocidad");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel5.setText("Ajuste la velocidad");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Ajuste la velocidad");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 1190, 170));

        jLabel25.setFont(new java.awt.Font("Rockwell Extra Bold", 0, 48)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("ARENA");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));

        roundCounterLabel.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        roundCounterLabel.setForeground(new java.awt.Color(255, 255, 255));
        roundCounterLabel.setText("0");
        jPanel1.add(roundCounterLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 70, -1, -1));

        jLabel29.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("ROUND:");
        jPanel1.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 730, 120));

        jPanel5.setBackground(new java.awt.Color(0, 102, 204));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        battleDurationSlider.setMajorTickSpacing(9);
        battleDurationSlider.setMaximum(20);
        battleDurationSlider.setMinimum(1);
        battleDurationSlider.setMinorTickSpacing(1);
        battleDurationSlider.setPaintLabels(true);
        battleDurationSlider.setPaintTicks(true);
        battleDurationSlider.setToolTipText("Slider de Velocidad");
        battleDurationSlider.setValue(10);
        battleDurationSlider.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        battleDurationSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                battleDurationSliderStateChanged(evt);
            }
        });
        jPanel5.add(battleDurationSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 60, 330, 60));

        jLabel8.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("AJUSTE LA VELOCIDAD");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("COLA DE REFUERZO 2");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        jPanel6.setBackground(new java.awt.Color(255, 51, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 330, 90));

        jScrollPane11.setViewportView(jScrollPane12);

        jPanel6.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 330, 90));
        jPanel6.add(jSlider4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 80, 330, 60));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel10.setText("Ajuste la velocidad");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel11.setText("Ajuste la velocidad");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 20, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setText("Ajuste la velocidad");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, -1));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 1190, 170));
        jPanel5.add(swReinQueue, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 260, 70));

        jLabel15.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("COLA DE REFUERZO 1");
        jPanel5.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));
        jPanel5.add(stReinQueue, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, 260, 70));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 1270, 140));

        FightPanel.setBackground(new java.awt.Color(238, 216, 216));
        FightPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IAStatusLabel.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        IAStatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        IAStatusLabel.setText("estado actual");
        FightPanel.add(IAStatusLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 490, -1, -1));

        IAStatusTitle.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 36)); // NOI18N
        IAStatusTitle.setText("IA STATUS: ");
        FightPanel.add(IAStatusTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        jLabel30.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jLabel30.setText("Vida actual: ");
        FightPanel.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, -1, -1));

        stFighterNameLabel.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        stFighterNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stFighterNameLabel.setText("NAME");
        FightPanel.add(stFighterNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 340, -1, -1));

        jLabel32.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        jLabel32.setText("Vida actual: ");
        FightPanel.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 380, -1, -1));

        swFighterNameLabel.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 24)); // NOI18N
        swFighterNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        swFighterNameLabel.setText("NAME");
        FightPanel.add(swFighterNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, -1, -1));

        winnerLabel.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 20)); // NOI18N
        winnerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        winnerLabel.setText("Ganador");
        FightPanel.add(winnerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 80, -1));

        SWFighterCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SWImageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SWFighterCard.add(SWImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 5, 190, 230));

        FightPanel.add(SWFighterCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 200, 240));

        STFighterCard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        STImageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        STFighterCard.add(STImageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 5, 180, 230));

        FightPanel.add(STFighterCard, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 190, 240));

        announcerLabel.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 18)); // NOI18N
        announcerLabel.setText("ANNOUNCER");
        FightPanel.add(announcerLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        swAgilityLabel.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 20)); // NOI18N
        swAgilityLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        swAgilityLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Assets/icons/agility32.png"))); // NOI18N
        swAgilityLabel.setText("0");
        FightPanel.add(swAgilityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel44.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 20)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Ganador");
        FightPanel.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 80, -1));

        swHPLabel.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 20)); // NOI18N
        swHPLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        swHPLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Assets/icons/heart32.png"))); // NOI18N
        swHPLabel.setText("0");
        FightPanel.add(swHPLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        swDefenseLabel.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 20)); // NOI18N
        swDefenseLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        swDefenseLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Assets/icons/shield32.png"))); // NOI18N
        swDefenseLabel.setText("0");
        FightPanel.add(swDefenseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        stHPLabel.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 20)); // NOI18N
        stHPLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        stHPLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Assets/icons/heart32.png"))); // NOI18N
        stHPLabel.setText("0");
        FightPanel.add(stHPLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, -1, -1));

        stDefenseLabel.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 20)); // NOI18N
        stDefenseLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        stDefenseLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Assets/icons/shield32.png"))); // NOI18N
        stDefenseLabel.setText("0");
        FightPanel.add(stDefenseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, -1, -1));

        stAgilityLabel.setFont(new java.awt.Font("Franklin Gothic Demi Cond", 0, 20)); // NOI18N
        stAgilityLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        stAgilityLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Assets/icons/agility32.png"))); // NOI18N
        stAgilityLabel.setText("0");
        FightPanel.add(stAgilityLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 210, -1, -1));

        getContentPane().add(FightPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 730, 540));

        SWQueuePanel.setBackground(new java.awt.Color(0, 0, 0));
        SWQueuePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        SWQueuePanel.add(swQueue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 210, 90));
        SWQueuePanel.add(swQueue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 210, 90));
        SWQueuePanel.add(swQueue3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 210, 90));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("COLA PRIORIDAD 3");
        SWQueuePanel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("COLA PRIORIDAD 1");
        SWQueuePanel.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel21.setBackground(new java.awt.Color(255, 255, 255));
        jLabel21.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("COLA PRIORIDAD 2");
        SWQueuePanel.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("VICTORIAS: 0");
        SWQueuePanel.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        SWLogoLabel.setForeground(new java.awt.Color(255, 255, 255));
        SWLogoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SWLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Assets/logos/starwars-logo.png"))); // NOI18N
        SWQueuePanel.add(SWLogoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 80));

        getContentPane().add(SWQueuePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 660));

        STQueuePanel.setBackground(new java.awt.Color(0, 0, 0));
        STQueuePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        STQueuePanel.add(stQueue1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 210, 90));
        STQueuePanel.add(stQueue2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 210, 90));
        STQueuePanel.add(stQueue3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 210, 90));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("COLA PRIORIDAD 3");
        STQueuePanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("COLA PRIORIDAD 1");
        STQueuePanel.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("COLA PRIORIDAD 2");
        STQueuePanel.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tw Cen MT", 1, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("VICTORIAS: 0");
        STQueuePanel.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        STLogoLabel.setForeground(new java.awt.Color(255, 255, 255));
        STLogoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        STLogoLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Assets/logos/startrek-logo.png"))); // NOI18N
        STQueuePanel.add(STLogoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 60));

        getContentPane().add(STQueuePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, 270, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void battleDurationSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_battleDurationSliderStateChanged
        // TODO add your handling code here:
        int newSpeed = this.getBattleDurationSlider().getValue();
        app.getApp().setBattleDuration(newSpeed);
    }//GEN-LAST:event_battleDurationSliderStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FightPanel;
    private javax.swing.JLabel IAStatusLabel;
    private javax.swing.JLabel IAStatusTitle;
    private javax.swing.JPanel STFighterCard;
    private javax.swing.JLabel STImageLabel;
    private javax.swing.JLabel STLogoLabel;
    private javax.swing.JPanel STQueuePanel;
    private javax.swing.JPanel SWFighterCard;
    private javax.swing.JLabel SWImageLabel;
    private javax.swing.JLabel SWLogoLabel;
    private javax.swing.JPanel SWQueuePanel;
    private javax.swing.JLabel announcerLabel;
    private javax.swing.JSlider battleDurationSlider;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSlider jSlider2;
    private javax.swing.JSlider jSlider4;
    private javax.swing.JLabel roundCounterLabel;
    private javax.swing.JLabel stAgilityLabel;
    private javax.swing.JLabel stDefenseLabel;
    private javax.swing.JLabel stFighterNameLabel;
    private javax.swing.JLabel stHPLabel;
    private javax.swing.JScrollPane stQueue1;
    private javax.swing.JScrollPane stQueue2;
    private javax.swing.JScrollPane stQueue3;
    private javax.swing.JScrollPane stReinQueue;
    private javax.swing.JLabel swAgilityLabel;
    private javax.swing.JLabel swDefenseLabel;
    private javax.swing.JLabel swFighterNameLabel;
    private javax.swing.JLabel swHPLabel;
    private javax.swing.JScrollPane swQueue1;
    private javax.swing.JScrollPane swQueue2;
    private javax.swing.JScrollPane swQueue3;
    private javax.swing.JScrollPane swReinQueue;
    private javax.swing.JLabel winnerLabel;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the mainFrameInstance
     */
    public static Principal getMainFrameInstance() {
        return mainFrameInstance;
    }

    /**
     * @param aMainFrameInstance the mainFrameInstance to set
     */
    public static void setMainFrameInstance(Principal aMainFrameInstance) {
        mainFrameInstance = aMainFrameInstance;
    }

    /**
     * @return the battleDurationSlider
     */
    public javax.swing.JSlider getBattleDurationSlider() {
        return battleDurationSlider;
    }

    /**
     * @param battleDurationSlider the battleDurationSlider to set
     */
    public void setBattleDurationSlider(javax.swing.JSlider battleDurationSlider) {
        this.battleDurationSlider = battleDurationSlider;
    }

    /**
     * @return the stQueue1
     */
    public javax.swing.JScrollPane getStQueue1() {
        return stQueue1;
    }

    /**
     * @param stQueue1 the stQueue1 to set
     */
    public void setStQueue1(javax.swing.JScrollPane stQueue1) {
        this.stQueue1 = stQueue1;
    }

    /**
     * @return the stQueue2
     */
    public javax.swing.JScrollPane getStQueue2() {
        return stQueue2;
    }

    /**
     * @param stQueue2 the stQueue2 to set
     */
    public void setStQueue2(javax.swing.JScrollPane stQueue2) {
        this.stQueue2 = stQueue2;
    }

    /**
     * @return the stQueue3
     */
    public javax.swing.JScrollPane getStQueue3() {
        return stQueue3;
    }

    /**
     * @param stQueue3 the stQueue3 to set
     */
    public void setStQueue3(javax.swing.JScrollPane stQueue3) {
        this.stQueue3 = stQueue3;
    }

    /**
     * @return the swQueue1
     */
    public javax.swing.JScrollPane getSwQueue1() {
        return swQueue1;
    }

    /**
     * @param swQueue1 the swQueue1 to set
     */
    public void setSwQueue1(javax.swing.JScrollPane swQueue1) {
        this.swQueue1 = swQueue1;
    }

    /**
     * @return the swQueue2
     */
    public javax.swing.JScrollPane getSwQueue2() {
        return swQueue2;
    }

    /**
     * @param swQueue2 the swQueue2 to set
     */
    public void setSwQueue2(javax.swing.JScrollPane swQueue2) {
        this.swQueue2 = swQueue2;
    }

    /**
     * @return the swQueue3
     */
    public javax.swing.JScrollPane getSwQueue3() {
        return swQueue3;
    }

    /**
     * @param swQueue3 the swQueue3 to set
     */
    public void setSwQueue3(javax.swing.JScrollPane swQueue3) {
        this.swQueue3 = swQueue3;
    }

    /**
     * @return the imagesManager
     */
    public ImagesManager getImagesManager() {
        return imagesManager;
    }

    /**
     * @param imagesManager the imagesManager to set
     */
    public void setImagesManager(ImagesManager imagesManager) {
        this.imagesManager = imagesManager;
    }

    /**
     * @return the announcerLabel
     */
    public javax.swing.JLabel getAnnouncerLabel() {
        return announcerLabel;
    }

    /**
     * @param announcerLabel the announcerLabel to set
     */
    public void setAnnouncerLabel(javax.swing.JLabel announcerLabel) {
        this.announcerLabel = announcerLabel;
    }

    /**
     * @return the roundCounterLabel
     */
    public javax.swing.JLabel getRoundCounterLabel() {
        return roundCounterLabel;
    }

    /**
     * @param roundCounterLabel the roundCounterLabel to set
     */
    public void setRoundCounterLabel(javax.swing.JLabel roundCounterLabel) {
        this.roundCounterLabel = roundCounterLabel;
    }

    /**
     * @return the stAgilityLabel
     */
    public javax.swing.JLabel getStAgilityLabel() {
        return stAgilityLabel;
    }

    /**
     * @param stAgilityLabel the stAgilityLabel to set
     */
    public void setStAgilityLabel(javax.swing.JLabel stAgilityLabel) {
        this.stAgilityLabel = stAgilityLabel;
    }

    /**
     * @return the stDefenseLabel
     */
    public javax.swing.JLabel getStDefenseLabel() {
        return stDefenseLabel;
    }

    /**
     * @param stDefenseLabel the stDefenseLabel to set
     */
    public void setStDefenseLabel(javax.swing.JLabel stDefenseLabel) {
        this.stDefenseLabel = stDefenseLabel;
    }

    /**
     * @return the stFighterNameLabel
     */
    public javax.swing.JLabel getStFighterNameLabel() {
        return stFighterNameLabel;
    }

    /**
     * @param stFighterNameLabel the stFighterNameLabel to set
     */
    public void setStFighterNameLabel(javax.swing.JLabel stFighterNameLabel) {
        this.stFighterNameLabel = stFighterNameLabel;
    }

    /**
     * @return the stHPLabel
     */
    public javax.swing.JLabel getStHPLabel() {
        return stHPLabel;
    }

    /**
     * @param stHPLabel the stHPLabel to set
     */
    public void setStHPLabel(javax.swing.JLabel stHPLabel) {
        this.stHPLabel = stHPLabel;
    }

    /**
     * @return the swAgilityLabel
     */
    public javax.swing.JLabel getSwAgilityLabel() {
        return swAgilityLabel;
    }

    /**
     * @param swAgilityLabel the swAgilityLabel to set
     */
    public void setSwAgilityLabel(javax.swing.JLabel swAgilityLabel) {
        this.swAgilityLabel = swAgilityLabel;
    }

    /**
     * @return the swDefenseLabel
     */
    public javax.swing.JLabel getSwDefenseLabel() {
        return swDefenseLabel;
    }

    /**
     * @param swDefenseLabel the swDefenseLabel to set
     */
    public void setSwDefenseLabel(javax.swing.JLabel swDefenseLabel) {
        this.swDefenseLabel = swDefenseLabel;
    }

    /**
     * @return the swFighterNameLabel
     */
    public javax.swing.JLabel getSwFighterNameLabel() {
        return swFighterNameLabel;
    }

    /**
     * @param swFighterNameLabel the swFighterNameLabel to set
     */
    public void setSwFighterNameLabel(javax.swing.JLabel swFighterNameLabel) {
        this.swFighterNameLabel = swFighterNameLabel;
    }

    /**
     * @return the swHPLabel
     */
    public javax.swing.JLabel getSwHPLabel() {
        return swHPLabel;
    }

    /**
     * @param swHPLabel the swHPLabel to set
     */
    public void setSwHPLabel(javax.swing.JLabel swHPLabel) {
        this.swHPLabel = swHPLabel;
    }

    /**
     * @return the winnerLabel
     */
    public javax.swing.JLabel getWinnerLabel() {
        return winnerLabel;
    }

    /**
     * @param winnerLabel the winnerLabel to set
     */
    public void setWinnerLabel(javax.swing.JLabel winnerLabel) {
        this.winnerLabel = winnerLabel;
    }

    /**
     * @return the IAStatusLabel
     */
    public javax.swing.JLabel getIAStatusLabel() {
        return IAStatusLabel;
    }

    /**
     * @param IAStatusLabel the IAStatusLabel to set
     */
    public void setIAStatusLabel(javax.swing.JLabel IAStatusLabel) {
        this.IAStatusLabel = IAStatusLabel;
    }

    /**
     * @return the STImageLabel
     */
    public javax.swing.JLabel getSTImageLabel() {
        return STImageLabel;
    }

    /**
     * @param STImageLabel the STImageLabel to set
     */
    public void setSTImageLabel(javax.swing.JLabel STImageLabel) {
        this.STImageLabel = STImageLabel;
    }

    /**
     * @return the SWImageLabel
     */
    public javax.swing.JLabel getSWImageLabel() {
        return SWImageLabel;
    }

    /**
     * @param SWImageLabel the SWImageLabel to set
     */
    public void setSWImageLabel(javax.swing.JLabel SWImageLabel) {
        this.SWImageLabel = SWImageLabel;
    }

}
